### ISSUE TITLE
Victory condition

### ISSUE THREAD

**Issue by Coolthulhu** [TGITS-Solutions/Cataclysm-DDA#30]
Any plans?

How about this:
* Exactly one special endgame lab per game, spawned in (0,0) overmap
* It has exactly x levels (5 sounds good)
* The finale has a portal
* You can either disable it or enter it and die (Freeman you fool!), both of which count as win
* When starting new game, it will try to place you within set distance of (0,0) overmap, to force you to walk but not too far

Having a victory condition - even a semi-trivial one like this - goes a long way towards giving a game a purpose and a timescale. Those in turn are a point of reference for balancing.

**Comment by TrainTurningPoint** [comment]
Hi @Coolthulhu.
I have some plans, but they are rather complex and probably won't be possible until some major changes in game mechanics.
They don't conflict with your proposal though, adding a special endgame lab is a necessary step which can be built upon later so there's no problem.

>When starting new game, it will try to place you within set distance of (0,0) overmap, to force you to walk but not too far

The only thing I dislike. I'd rather have it be the opposite, so the player spawn no closer than a set distance:
- spawning within a set distance from (0,0) would limit the number of possible spawn points for the character, which is a problem for people who don't reset the world on dying or have multiple characters in the same world
- it's supposed to be endgame content, finding it too early would not be a good thing for player since he can't benefit from it yet and some more useful location might have spawned there instead
- whatever the intended timescale will be, I'm not expecting player to win before being able to travel the overworld freely anyway

Overall, please do go ahead. I was planning to tackle winning conditions much later, but there's no reason not to do it now if you are interested.
